[package]
name = "raqim-siege"
version = "0.1.0"
edition = "2024"

[dependencies]

tokio = { version = "1.37", features = ["rt-multi-thread", "macros", "net", "io-util", "time", "sync"] }

hex = "0.4"
rkyv = "0.8.15"

md-5 = "0.11"
serde = { version = "1.0", features = ["derive"] }
ed25519-dalek = {version = "2.2.0", default-features = false, features = ["rand_core", "serde"]}
rand_core = { version = "0.6", features = ["getrandom"] }

postcard = "1.1.3"