[package]
name = "synapse-core"
version = "0.1.0"
edition = "2024"

[dependencies]
# The Zero-copy Data plane
rkyv = "0.8.15"

# The shared memory substrate
iceoryx2 = "0.8.1"

# The State Engine (CRDTs)
loro = "1.0"

# The Nucleus Async Runtime
tokio = {version = "1", features = ["full"]}

blake3 =  "1.5"

zenoh = "1.7.2"

hex =  "0.4"
uuid = { version = "1.8", features = ["v4"] }

lancedb = "0.9"
arrow-array = "52.2"
arrow-schema = "52.2"

wasmtime = "18.0"
anyhow = "1.0"

fastembed = "3.1.1"

futures = "0.3"
clap = { version = "4.5", features = ["derive", "env"] } # For CLI parsing
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
memmap2 = "0.9" 
tokio-uring = "0.4"