apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: raqim 
spec: 
  serviceName: "raqim-headless" 
  replicas: {{ .Values.replicaCount }}
  selector: 
    matchLabels: 
      app: raqim-core 
    template: 
      metadata: 
        labels: 
          app: raqim-core 
      spec: 
      # High Availability Anti-Affinity. Forces K8s to spread the swarm across different physical servers.
        affinity: 
          podAntiAffinity: 
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector: 
                  matchExpressions: 
                    - key: app 
                      operator: In 
                      values: 
                        - raqim-core 
                topologyKey: "kubernetes.io/hostname"

        # Zero-Trust Security context
        securityContext: 
          runAsNonRoot: true 
          runAsUser: 1000
          fgGroup: 1000


        containers: 
          - name: raqim-core 
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }} 
            env: 
             - name: RAQIM_TENANT_ALIAS
               value: {{ .Values.config.tenantAlias | quote }}
             - name: RAQIM_LICENSE_KEY
               value: {{ .Values.config.license_key | quote }}
            ports:  
              - containerPort: 8080
                name: firehose 
              - containerPort: 8081
                name: admin 
              - containerPort: 7447
                name: zenoh

            # Mounting the Persistent Brain
            volumeMounts: 
              - name: raqim-data
                mountPath: /var/lib/raqim/data

  # The NVMe Hard Drive Requisition
  volumeClaimTemplates: 
    - metadata: 
        name: raqim-data
      spec: 
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.storage.className }}
        resources: 
          requests: 
            storage: {{.Values.storage.size}}
